@host = http://localhost:5122
@tripId = 442c6348-4490-43e8-9827-17a57a37de44

### Generate trip

POST {{host}}/api/trips/generate
Accept: application/json
Content-Type: application/json

{
  "destination": "Japan",
  "numberOfDays": 5,
  "budget": 2500,
  "currency": "USD",
  "interests": [
    "food",
    "technology"
  ]
}

### Get trip by id

GET {{host}}/api/trips/{{tripId}}
Accept: application/json

### List trips

GET {{host}}/api/trips/trips
Accept: application/json

### Validate trip

POST {{host}}/api/trips/{{tripId}}/validate
Accept: application/json

### Generate trip - invalid request

POST {{host}}/api/trips/generate
Accept: application/json
Content-Type: application/json

{
  "destination": "",
  "numberOfDays": 0,
  "budget": 0,
  "currency": "US",
  "interests": []
}